name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build x64
    runs-on: ubuntu-20.04
    steps:
      - name: OW Repo clone
        uses: actions/checkout@v1
      - name: Bootstrap
        run: sudo apt-get install dosbox && OWDOSBOX=dosbox ./build.sh rel
      - name: Make executable (binl)
        run: while read e; do echo rel/binl/$e; done < exelist | xargs chmod a+x
      - name: Make executable (binl64)
        run: while read e; do echo rel/binl64/$e; done < exelist | xargs chmod a+x || true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rel
          path: |
            rel/*
